server:
    port: 9002

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:toyota_finans}?currentSchema=market_data
        username: ${POSTGRES_USER:toyota}
        password: ${POSTGRES_PASSWORD:toyota}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                default_schema: market_data
    flyway:
        enabled: true
        schemas: market_data
        default-schema: market_data
        create-schemas: true

eureka:
    client:
        register-with-eureka: true
        fetch-registry: false
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}